# Generated by Django 4.1 on 2023-02-21 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='link',
        ),
        migrations.AddField(
            model_name='artist',
            name='release_date',
            field=models.CharField(default='release_date', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.CharField(max_length=5000),
        ),
    ]
