# Generated by Django 4.1 on 2023-02-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists_api', '0002_remove_artist_link_artist_release_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='category',
            field=models.CharField(default='category', max_length=100),
            preserve_default=False,
        ),
    ]
